### ISSUE TITLE
Question: given a struct numpy array in memory, what's the easiest way to write them to an aedat4 file?

### ISSUE THREAD

**Issue by biphasic** [neuromorphicsystems/aedat#13]
I would like to do some benchmarking between file reading packages and file formats and for that I need to write the same events to a file using different encodings, aedat4 being one of them. What's the easiest way to achieve this that you know of? Thank you!

**Comment by aMarcireau** [comment]
None of the AEDAT libraries I know (this library, https://github.com/norse/aestream, and https://gitlab.com/inivation/dv/dv-python) can encode events. This is partly due to the relative complexity of AEDAT, which supports three compression modes (raw, LZ4 and ZSTD).

These different encodings are likely to impact performance (size, compression speed, and to a lesser extent decompression speed).

You may have to write a custom AEDAT generator for your benchmark. AEDAT uses flatbuffers (https://google.github.io/flatbuffers/) so this should be relatively straightforward, especially if you only implement event packets and ioheaders. The latter provides information about the compression type. The other packet types are frame, imus, ioheader, and triggers. This repository contains a copy of the flatbuffer schemas for AEDAT: https://github.com/neuromorphicsystems/aedat/tree/master/flatbuffers

**Comment by biphasic** [comment]
Great thank you for that info and clarification. I think for the moment then I'll just take an aedat4 file as the baseline, read the events and then generate all the other formats with the respective libraries.
