### ISSUE TITLE
reshape error occurred when implementing 'for packet in decoder:'

### ISSUE THREAD

**Issue by GEN418** [neuromorphicsystems/aedat#9]
Hello:
        I have converted some aedat2 files recorded by DAVIS 346 RED into aedat4 files through DV platform, when implementing 'for packet in decoder:' for the converted files, the error occurred: "cannot reshape array of size 269880 into shape (260,346)", I assumed that the decoder treat the RGB APS frames as gray scale frames, so how to solve it.

**Comment by Arturjssln** [comment]
Same problem, and also recording with DAVIS 346 red

**Comment by aMarcireau** [comment]
Hello,

This indeed looks like an RGB issue. As I don't have access to a DAVIS RED, could you send me an RGB AEDAT 4 recording so that I may add support for it to this library?

In the meantime, https://gitlab.com/inivation/dv/dv-python probably supports DAVIS RED data already. Its pure-python implementation means that it is slower, but that may not be a major problem depending on your use case.

**Comment by aMarcireau** [comment]
Hi all,

I published a new version on Pypi (https://pypi.org/project/aedat/) that should fix this issue. Feel free to re-open the issue if the fix does not work.
